spring:
  datasource:
    url: jdbc:mysql://localhost:3306/credbank
    username: admin
    password: admin
  liquibase:
    change-log: classpath:/config/liquibase/master.xml
    enabled: true

server:
  port: 8080
